const SERVER_ERRORS = {
  VEHICLE_NOT_FOUND: 0,
  VEHICLE_ADDED_FAILED: 1,
  VEHICLE_UPDATED_FAILED: 2,
  VEHICLE_DELETED_FAILED: 3,
  VEHICLE_MAINTENANCE_ADDED_FAILED: 4,
  VEHICLE_MAINTENANCE_NOT_FOUND: 5,
  VEHICLE_USAGE_NOT_FOUND: 6,
  VEHICLE_USAGE_ADDED_FAILED: 7,
  SERVER_ERROR: 8,
};
export default SERVER_ERRORS;
